/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg8.puzzle;

import java.awt.List;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * H A N D M A D E from Love by
 * @author Achmad Ade Nugroho
 * @member Taqiyuddin Nursy, Khafid Ghonio
 */
public class Gui8Puzzle extends javax.swing.JFrame {

    /**
     * Creates new form Gui8Puzzle
     */
    String[][] petakpuzzle = {
        {"1", "5", "2"},
        {"4", "", "3"},
        {"7", "8", "6"}
    };
    String[][] finalpuzzle = {
        {"1", "2", "3"},
        {"4", "5", "6"},
        {"7", "8", ""}
    };
    public Gui8Puzzle() {
        initComponents();
        setTitle("The 8 Puzzle");
        setAlwaysOnTop(true);
        //petakpuzzle = shufflearray(petakpuzzle);
        jButton1.setText(petakpuzzle[0][0]);
        jButton2.setText(petakpuzzle[0][1]);
        jButton3.setText(petakpuzzle[0][2]);
        jButton4.setText(petakpuzzle[1][0]);
        jButton5.setText(petakpuzzle[1][1]);
        jButton6.setText(petakpuzzle[1][2]);
        jButton7.setText(petakpuzzle[2][0]);
        jButton8.setText(petakpuzzle[2][1]);
        jButton9.setText(petakpuzzle[2][2]);
        
        jButton1.setFocusable(false);
        jButton2.setFocusable(false);
        jButton3.setFocusable(false);
        jButton4.setFocusable(false);
        jButton5.setFocusable(false);
        jButton6.setFocusable(false);
        jButton7.setFocusable(false);
        jButton8.setFocusable(false);
        jButton9.setFocusable(false);
        jButton10.setFocusable(false);
        jButton11.setFocusable(false);
        
        //jButton10.setEnabled(false);
        
        if(jButton1.getText().equals("")){
            jButton1.setEnabled(false);
        }
        if(jButton2.getText().equals("")){
            jButton2.setEnabled(false);
        }
        if(jButton3.getText().equals("")){
            jButton3.setEnabled(false);
        }
        if(jButton4.getText().equals("")){
            jButton4.setEnabled(false);
        }
        if(jButton5.getText().equals("")){
            jButton5.setEnabled(false);
        }
        if(jButton6.getText().equals("")){
            jButton6.setEnabled(false);
        }
        if(jButton7.getText().equals("")){
            jButton7.setEnabled(false);
        }
        if(jButton8.getText().equals("")){
            jButton8.setEnabled(false);
        }
        if(jButton9.getText().equals("")){
            jButton9.setEnabled(false);
        }

        //requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("1");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("5");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("2");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("4");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setText("3");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setText("7");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("8");

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setText("6");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        jButton10.setText("AUTO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("CHECK FALSE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            if(jButton1.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton2.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton3.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton4.isEnabled() == false){
                swapButton(jButton1, jButton4);
            }
            else if(jButton5.isEnabled() == false){
                swapButton(jButton2, jButton5);
            }
            else if(jButton6.isEnabled() == false){
                swapButton(jButton3, jButton6);
            }
            else if(jButton7.isEnabled() == false){
                swapButton(jButton4, jButton7);
            }
            else if(jButton8.isEnabled() == false){
                swapButton(jButton5, jButton8);
            }
            else if(jButton9.isEnabled() == false){
                swapButton(jButton6, jButton9);
            }
        }
        else if(evt.getKeyCode() == KeyEvent.VK_UP){
            if(jButton1.isEnabled() == false){
                swapButton(jButton4, jButton1);
            }
            else if(jButton2.isEnabled() == false){
                swapButton(jButton2, jButton5);
            }
            else if(jButton3.isEnabled() == false){
                swapButton(jButton6, jButton3);
            }
            else if(jButton4.isEnabled() == false){
                swapButton(jButton7, jButton4);
            }
            else if(jButton5.isEnabled() == false){
                swapButton(jButton5, jButton8);
            }
            else if(jButton6.isEnabled() == false){
                swapButton(jButton6, jButton9);
            }
            else if(jButton7.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton8.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton9.isEnabled() == false){
                getToolkit().beep();
            }
        }
        else if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            if(jButton1.isEnabled() == false){
                swapButton(jButton1, jButton2);
            }
            else if(jButton2.isEnabled() == false){
                swapButton(jButton2, jButton3);
            }
            else if(jButton3.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton4.isEnabled() == false){
                swapButton(jButton5, jButton4);
            }
            else if(jButton5.isEnabled() == false){
                swapButton(jButton5, jButton6);
            }
            else if(jButton6.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton7.isEnabled() == false){
                swapButton(jButton7, jButton8);
            }
            else if(jButton8.isEnabled() == false){
                swapButton(jButton8, jButton9);
            }
            else if(jButton9.isEnabled() == false){
                getToolkit().beep();
            }
        }
        else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            if(jButton1.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton2.isEnabled() == false){
                swapButton(jButton2, jButton1);
            }
            else if(jButton3.isEnabled() == false){
                swapButton(jButton3, jButton2);
            }
            else if(jButton4.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton5.isEnabled() == false){
                swapButton(jButton5, jButton4);
            }
            else if(jButton6.isEnabled() == false){
                swapButton(jButton6, jButton5);
            }
            else if(jButton7.isEnabled() == false){
                getToolkit().beep();
            }
            else if(jButton8.isEnabled() == false){
                swapButton(jButton8, jButton7);
            }
            else if(jButton9.isEnabled() == false){
                swapButton(jButton9, jButton8);
            }
        }
        
        /*if(evt.getKeyCode() == KeyEvent.VK_INSERT){
            String[][] pzl = {
                {"1", "2", "3"},
                {"4", "5", "6"},
                {"7", "8", ""}
            };
            jButton1.setText(pzl[0][0]);
            jButton2.setText(pzl[0][1]);
            jButton3.setText(pzl[0][2]);
            jButton4.setText(pzl[1][0]);
            jButton5.setText(pzl[1][1]);
            jButton6.setText(pzl[1][2]);
            jButton7.setText(pzl[2][0]);
            jButton8.setText(pzl[2][1]);
            jButton9.setText(pzl[2][2]);
        }*/
        if(evt.getKeyCode() == KeyEvent.VK_F5){
            dispose();
            Gui8Puzzle gp = new Gui8Puzzle();
            gp.looknfeel();
            gp.setVisible(true);
        }
        if(isSolved(getStatesButton())){
            //showRestart();
        }
    }//GEN-LAST:event_formKeyPressed

    private void showRestart(){
        int pil = JOptionPane.showConfirmDialog(this, "Ingin Mengulang Permainan?", "Reload Game?", JOptionPane.YES_NO_OPTION);
        if(pil == JOptionPane.YES_OPTION){
            dispose();
            Gui8Puzzle gp = new Gui8Puzzle();
            gp.looknfeel();
            gp.setVisible(true);
        } else if(pil == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Terima kasih telah bermain");
            dispose();
        }
    }
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.out.println("Bekerja...");
        //System.out.println(e.toString());
        System.out.println("Solved?: " + isSolved(getStatesButton()));
        while(!isSolved(getStatesButton())){
            System.out.println("Swapping berjalan...");
            //String[][] states = getStatesButton();
            if(jButton1.isEnabled() == false){
                int false_state, false_state2;
                
                swapButton(jButton1, jButton4);
                false_state = getFalseState();
                swapButton(jButton4, jButton1);
                swapButton(jButton1, jButton2);
                false_state2 = getFalseState();
                swapButton(jButton2, jButton1);
                
                //resetDisable();
                
                if(false_state < false_state2){
                    swapButton(jButton1, jButton4);
                    System.out.println("Swapped 1 -> 4");
                } else {
                    swapButton(jButton1, jButton2);
                    System.out.println("Swapped 1 -> 2");
                }
            } else if (jButton3.isEnabled() == false){
                int false_state, false_state2;
                
                swapButton(jButton3, jButton2);
                false_state = getFalseState();
                swapButton(jButton2, jButton3);
                swapButton(jButton3, jButton6);
                false_state2 = getFalseState();
                swapButton(jButton6, jButton3);
                
                //resetDisable();
                
                if(false_state < false_state2){
                    swapButton(jButton3, jButton2);
                    System.out.println("Swapped 3 -> 2");
                } else {
                    swapButton(jButton3, jButton6);
                    System.out.println("Swapped 3 -> 6");
                }
            } else if (jButton9.isEnabled() == false){
                int false_state, false_state2;
                
                swapButton(jButton9, jButton6);
                false_state = getFalseState();
                swapButton(jButton6, jButton9);
                swapButton(jButton9, jButton8);
                false_state2 = getFalseState();
                swapButton(jButton8, jButton9);
                
                //resetDisable();
                
                if(false_state < false_state2){
                    swapButton(jButton9, jButton6);
                    System.out.println("Swapped 9 -> 6");
                } else {
                    swapButton(jButton9, jButton8);
                    System.out.println("Swapped 9 -> 8");
                }
            } else if (jButton7.isEnabled() == false){
                int false_state, false_state2;
                
                swapButton(jButton7, jButton4);
                false_state = getFalseState();
                swapButton(jButton4, jButton7);
                
                swapButton(jButton7, jButton8);
                false_state2 = getFalseState();
                swapButton(jButton8, jButton7);
                
                //resetDisable();
                
                if(false_state < false_state2){
                    swapButton(jButton7, jButton4);
                    System.out.println("Swapped 7 -> 4");
                } else {
                    swapButton(jButton7, jButton8);
                    System.out.println("Swapped 7 -> 8");
                }
            } else if (jButton2.isEnabled() == false){
                int[] false_state = {0,0,0};
                
                swapButton(jButton2, jButton1);
                false_state[0] = getFalseState();
                swapButton(jButton1, jButton2);
                
                swapButton(jButton2, jButton5);
                false_state[1] = getFalseState();
                swapButton(jButton5, jButton2);
                
                swapButton(jButton2, jButton3);
                false_state[2] = getFalseState();
                swapButton(jButton3, jButton2);
                
                //resetDisable();
                
                int kecil = Math.min(false_state[0], Math.min(false_state[1], false_state[2]));
                if(false_state[0] == kecil){
                    swapButton(jButton2, jButton1);
                    System.out.println("Swapped 2 -> 1");
                } else if(false_state[1] == kecil){
                    swapButton(jButton2, jButton5);
                    System.out.println("Swapped 2 -> 5");
                } else {
                    swapButton(jButton2, jButton3);
                    System.out.println("Swapped 2 -> 3");
                }
            } else if (jButton6.isEnabled() == false){
                int[] false_state = {0,0,0};
                
                swapButton(jButton6, jButton3);
                false_state[0] = getFalseState();
                swapButton(jButton3, jButton6);
                
                swapButton(jButton6, jButton5);
                false_state[1] = getFalseState();
                swapButton(jButton5, jButton6);
                
                swapButton(jButton6, jButton9);
                false_state[2] = getFalseState();
                swapButton(jButton9, jButton6);
                
                int kecil = Math.min(false_state[0], Math.min(false_state[1], false_state[2]));
                if(false_state[0] == kecil){
                    swapButton(jButton6, jButton3);
                    System.out.println("Swapped 6 -> 3");
                } else if (false_state[1] == kecil){
                    swapButton(jButton6, jButton5);
                    System.out.println("Swapped 6 -> 5");
                } else {
                    swapButton(jButton6, jButton9);
                    System.out.println("Swapped 6 -> 9");
                }
            } else if (jButton8.isEnabled() == false){
                int[] false_state = {0,0,0};
                
                swapButton(jButton8, jButton9);
                false_state[0] = getFalseState();
                swapButton(jButton9, jButton8);
                
                swapButton(jButton8, jButton5);
                false_state[1] = getFalseState();
                swapButton(jButton5, jButton8);
                
                swapButton(jButton8, jButton7);
                false_state[2] = getFalseState();
                swapButton(jButton7, jButton8);
                
                //resetDisable();
                
                int kecil = Math.min(false_state[0], Math.min(false_state[1], false_state[2]));
                if(false_state[0] == kecil){
                    swapButton(jButton8, jButton9);
                    System.out.println("Swapped 8 -> 9");
                } else if (false_state[1] == kecil){
                    swapButton(jButton8, jButton5);
                    System.out.println("Swapped 8 -> 5");
                } else {
                    swapButton(jButton8, jButton7);
                    System.out.println("Swapped 8 -> 7");
                }
            } else if (jButton4.isEnabled() == false){
                int[] false_state = {0,0,0};
                
                swapButton(jButton4, jButton7);
                false_state[0] = getFalseState();
                swapButton(jButton7, jButton4);
                
                swapButton(jButton4, jButton5);
                false_state[1] = getFalseState();
                swapButton(jButton5, jButton4);
                
                swapButton(jButton4, jButton1);
                false_state[2] = getFalseState();
                swapButton(jButton1, jButton4);
                
                //resetDisable();
                
                int kecil = Math.min(false_state[0], Math.min(false_state[1], false_state[2]));
                if(false_state[0] == kecil){
                    swapButton(jButton4, jButton7);
                    System.out.println("Swapped 4 -> 7");
                } else if (false_state[1] == kecil){
                    swapButton(jButton4, jButton5);
                    System.out.println("Swapped 4 -> 5");
                } else {
                    swapButton(jButton4, jButton1);
                    System.out.println("Swapped 4 -> 1");
                }
            } else if (jButton5.isEnabled() == false){
                int[] false_state = {0,0,0,0};
                
                swapButton(jButton5, jButton2);
                false_state[0] = getFalseState();
                swapButton(jButton2, jButton5);
                
                swapButton(jButton5, jButton6);
                false_state[1] = getFalseState();
                swapButton(jButton6, jButton5);
                
                swapButton(jButton5, jButton8);
                false_state[2] = getFalseState();
                swapButton(jButton8, jButton5);
                
                swapButton(jButton5, jButton4);
                false_state[3] = getFalseState();
                swapButton(jButton4, jButton5);
                
                //resetDisable();
                
                int kecil = Math.min(false_state[0], Math.min(false_state[1], Math.min(false_state[2], false_state[3])));
                if(false_state[0] == kecil){
                    swapButton(jButton5, jButton2);
                    System.out.println("Swapped 5 -> 2");
                } else if (false_state[1] == kecil){
                    swapButton(jButton5, jButton6);
                    System.out.println("Swapped 5 -> 6");
                } else if (false_state[2] == kecil){
                    swapButton(jButton5, jButton8);
                    System.out.println("Swapped 5 -> 8");
                } else {
                    swapButton(jButton5, jButton4);
                    System.out.println("Swapped 5 -> 4");
                }
            }
            try{
                Thread.sleep(1000);
            } catch (InterruptedException e){
                e.getMessage();
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Terdapat Ketidakcocokan sebanyak: " + getFalseState());
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void looknfeel() {
        /* Set the Nimbus look and feel */
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    public static String[][] shufflearray(String[][] array){
        Random r = new Random();
        
        for (int i = 0; i < array.length; i++){
            for(int j = 0; j < array[i].length; j++){
                int rndm2 = r.nextInt(array[i].length);
                int rndm1 = r.nextInt(array.length);
                String tmp = array[i][j];
                array[i][j] = array[rndm1][rndm2];
                array[rndm1][rndm2] = tmp;
            }
        }
        return array;
    }
    
    public boolean isSolved(String[][] states){
        int falseresult = 0;
        for(int i = 0; i<3; i++){
            for(int j = 0; j<3; j++){
                if(!getStatesButton()[i][j].equals(finalpuzzle[i][j])){
                    falseresult++;
                }
            }
        }
        if(falseresult > 0){
            return false;
        } else {
            JOptionPane.showMessageDialog(this, "Selamat Anda telah menyelesaikan 8 Puzzle");
            showRestart();
            return true;
        }
    }
    
    public String[][] getStatesButton(){
        String[][] e = {
            {jButton1.getText(), jButton2.getText(), jButton3.getText()},
            {jButton4.getText(), jButton5.getText(), jButton6.getText()},
            {jButton7.getText(), jButton8.getText(), jButton9.getText()}
        };
        return e;
    }
    
    public int getFalseState(){
        int result = 0;
        for(int i = 0; i<3; i++){
            for(int j = 0; j<3; j++){
                if(!getStatesButton()[i][j].equals(finalpuzzle[i][j])){
                    result++;
                }
            }
        }
        return result;
    }
    
    public void swapButton(JButton source, JButton dest){
        String tmp = source.getText();
        source.setText(dest.getText());
        dest.setText(tmp);
        if(source.isEnabled() == true)
            source.setEnabled(false);
        else 
            source.setEnabled(true);
        if(dest.isEnabled() == false)
            dest.setEnabled(true);
        else 
            dest.setEnabled(false);
    }
    
    public void resetDisable(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
